### PR TITLE
Nicks changes

### PR DESCRIPTION
**Pull request by nimkamp**
Youtube and Reddit parser.

### CODE REVIEW

**Comment by scottPlusPlus** [comment]
Seems like there are merge conflicts.  Can you resolve?

**Comment by nimkamp** [comment]
Yes I can. I forgot to merge into my branch. I am not sure why pulling from
main won't update the branch and I have to switch branch to get the latest
haha. I also tried resolving the merge conflicts this morning and I
completely butchered it. I will spend time later today figuring out why I
broke it. I might just checkout a previous hash and try to resolve again.

**Comment by nimkamp** [comment]
I just reverted the changes. I am going to take a stab at it again.

**Comment by nimkamp** [comment]
Looks like there was a missing try in the tr/catch block. I just added it
in. I will submit the pr for it now.

**Comment by nimkamp** [comment]
Can you also send me a twitter api key? I haven't received anything from
them yet.

**Pull request merged**
